### ISSUE TITLE
Moderation check fails on Ted Talk content

### ISSUE THREAD

**Issue by Shoooop** [TomFrankly/pipedream-notion-voice-notes#9] opened 2023-09-26 02:51 UTC
I created an MP3 of a popular Ted Talk video "How to speak so that people want to listen | Julian Treasure" (38M views) ([https://www.youtube.com/watch?v=eIho2S0ZahI](https://www.youtube.com/watch?v=eIho2S0ZahI)) that's about 10 minutes long. The workflow throws a moderation error on the content, however looking at the transcript there doesn't seem to be anything inappropriate mentioned. Thoughts?

Error
An error occurred while performing a moderation check on the transcript: An error occurred while performing a moderation check on chunk 5. The content of this chunk is as follows: It's hard to listen when somebody's that negative. And another form of negativity, complaining. Well, this is the national art of the UK. It's our national sport. Error message: Detected inappropriate content in the transcript chunk. Summarization on this file cannot be completed. The content of this chunk is as follows: It's hard to listen when somebody's that negative. And another form of negativity, complaining. Well, this is the national art of the UK. It's our national sport.  
    at Object.moderationCheck (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:658:11)
    at Object.run (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1907:4)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

**Comment by TomFrankly** [comment] 2023-09-26 02:58
You're right, I'm not seeing anything objectionable there.

If you go into Advanced Settings, you can actually disable the moderation check. Might be worth doing! Right now, I just throw an error if the moderation endpoint returns "flagged: true" - perhaps it can be modulated to only throw the error on a specific threshold. I'll need to look into that!

**Comment by Shoooop** [comment] 2023-09-26 03:30
Hmm, same moderation error, even with the Disable Moderation flag set to true in the Advanced Settings. Might just be a false positive on the OpenAI side. I'll do a few more tests using the Youtube-->MP3 approach, as well as with personal voice notes and see how things go. Thanks again Thomas, really impressed with the workflow and resulting notes!

**Comment by TomFrankly** [comment] 2023-09-26 05:06
Could you double-check that Disable Moderation Check is set to True?

Here I've just done a run with it set to True, and the logs are lacking the moderation check:

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/a6ea14da-e72f-4a7d-ab45-35c5dd9bb4b9)

And here I've set it to false, and I can see the moderation log:

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/79460251-5551-4ac8-96cf-a8e40be5a5d2)

That error text is a message I wrote in the code, so it can only show up if this code is allowed to run:

```
if (this.disable_moderation_check !== true) {
			await this.moderationCheck(fileInfo.full_transcript, openai);
		}
```

And if disable_moderation_check is true, then it won't run.

**Comment by Shoooop** [comment] 2023-09-28 19:23
@TomFrankly, i got around to testing again, and here's the output with Disable Moderation Check set to True. Same output with the variable set to lower case "true". both sets of logs show the Moderation step executing. Perhaps there's a bug/trick in read reading the field value?  ¯\\_(ツ)_/¯

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146048808/ef10fb9a-1d2c-4cd7-9442-0dbe678838b2)

**Comment by TomFrankly** [comment] 2023-09-28 20:08
@Shoooop did you actually type "True" there?

My UI looks different; there's actually a True/False toggle, essentially.

I found that I can type "True" as well, but that's not the intended behavior. It should have just given you a True button to click.

![CleanShot 2023-09-28 at 14 07 05@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/d8d1a381-c9e7-47d6-9d6a-cfdc29201e9a)

**Comment by Shoooop** [comment] 2023-09-29 14:36
Boom, that did the trick, however i have to admit the config UI is a bit finicky. It took a number of attempts of clicking of the Clear and Reset To Default buttons and jumping in and out of the control before the TRUE and FALSE options showed up. Once i selected TRUE and reran the workflow the Moderation Check indeed does not run. Thanks for helping debug this.

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146048808/4f5e9bc2-68fe-4a1a-bccd-3d10d2702488)

**Comment by TomFrankly** [comment] 2023-10-02 22:18
Just an update to close this:

I've shipped a new version that disables the moderation check by default. It was causing more problems than it was worth.

Here are the release notes for the newest version: https://github.com/TomFrankly/pipedream-notion-voice-notes/releases/tag/v0.7.0

**Closed by TomFrankly** 2023-10-02 22:18 UTC
